* 机器学习实战第一章

** 什么是机器学习，基本概念
*** 标称型和数值型
监督学习一般使用两种类型的目标变量（目标变量就是分类结果，别称）：标称型和数值型。
标称型，目标变量在一个有限集合选一个值；
数值型，目标变量在无限集合中选一个值，多用于回归分析。

*** 机器学习的过程就是：
-----------------------------------------
1） 选取一个函数集合
2） 用训练集和损失（评价）函数来选取最好的一个函数
3） 用这个函数预测新的数据
-----------------------------------------

*** 知识表示
知识表示，就是计算机学到一些东西之后，能做出自己的判断。
也就是计算机可以自己做些事情来“ _表达意见_ ”就叫做知识表示。

知识表示有些很容易被人理解，有些则不是。
知识表示可以采用 _规则集_ 或者 _概率分布_ 两种形式来表示。

** 机器学习的主要任务
回归主要用于预测数值型的目标变量。
常见的回归就是： _给定一些点，找到其最优拟合曲线_ 。

分类和回归属于监督学习。
监督学习必须知道【目标变量的分类信息】
无监督学习就是【不知道目标变量的分类信息】也没有【目标变量的值】
无监督学习常见用途：
1. 聚类：对数据分组
2. 密度估计：寻找描述数据统计值
3. 减少数据特征的维度，方便二维三维可视化。用于执行分类回归聚类密度估计的算法

*** 监督学习和非监督学习
监督学习：
1. k 近邻 --- 线性回归
2. 朴素贝叶斯 --- 局部加权线性回归
3. SVM --- Ridge 回归
4. 决策树 --- Lasso 最小回归系数估计

非监督学习：
1. k 均值 --- 最大期望算法
2. DBSCAN --- Parzen 窗设计

*** 如何选择合适的算法

选择算法就要回答两个问题：

**** 1. 这个算法的目的是什么？要完成什么任务？
1） 是否要预测目标变量的值？yes -- supervised
2） 目标变量什么类型？ 离散的 --- 分类器算法； 连续的 --- 回归算法
3） 是否要预测目标变量的值？no --- unsupervised
4） 是否只要分组？ 聚类算法
5） 是否分组还要估计数据与每个分组的相似程度？ 密度估计算法

**** 2. 需要分析或收集的数据（特征值）是什么？
1） 离散 or 连续？
2） 有否缺失？
3） 某个特征出现的频率？
4） 有否异常值（离群点）？
总结： 这两个问题都是在缩小我们选择的函数的范围。

** 开发机器学习程序的步骤

1）收集数据：网络爬虫，公开数据，设备数据等等。
2）准备输入数据：数据格式，某些语言 or 算法的独特要求：目标变量和特征值是字符串型 or 数值型。
3）分析输入数据：需要人工查看数据看有无【空值】or【明显的异常值】or【通过二维三维图像展示数据】
4）训练算法：将前三步得到的特定格式的数据，输入到算法，得到【知识 or 信息】，这个知识 or 信息需要存储为计算机可以处理的格式。
5）测试算法：评价算法是否符合要求。
6）使用算法：用实际情况检测算法看算法是否正常运行，看还有无需要改进的地方。

** Numpy 函数库基础
_Numpy 函数库存在两种不同的数据类型：matrix 和 array。_

1) 他们都可以处理【行列表示的数字元素】；

2) 两者不等价，在他们的实例上执行 _相同的数学_ 运算会得到 _不同的结果_ ；

3) 调用 mat() 可以把【数组】转换成【矩阵】；
   #+BEGIN_SRC python
   >>> random.rand(4,4)
   >>> array([[xxxx],[xxxx],[xxxx],[xxxx]])
   >>> randMat = mat(random.rand(4,4))
   >>> matrix([[xxxx],[xxxx],[xxxx],[xxxx]])
   #+END_SRC
4） ~.I~ 操作符实现了求【逆矩阵】运算
   : >>> randMat.I
5)  ~*~ 操作符实现了求【矩阵乘法】的运算
6) ~eye(4)~ 创建 4*4 的单位矩阵
