* Guowengui

:Reference:
1. [[https://www.wikiwand.com/zh-tw/%25E4%25B8%25AD%25E5%259B%25BD%25E4%25BA%25BA%25E6%25B0%2591%25E8%25A7%25A3%25E6%2594%25BE%25E5%2586%259B%25E4%25B8%258A%25E5%25B0%2586][wiki:中国人民解放军上将]]
:END:

  1. 中国人民解放军上将是中国人民解放军的最高军衔。
  2. 郭伯雄(武警司令，直接归政法委管理)
  3. 上将自杀自开国这是第一次,直接体现一个信号
  4. 美国国家强盛的表现是外交做的好;
  5. 中国国家强盛的表现是内斗给捋顺了;
  6. 老毛每天读那么多资治通鉴，史记，干什么的，就是学习怎么捋顺内部斗争;
  7. 现在中国真正在内斗的都是王岐山这样的人物，他在反腐么，反腐是内斗的利器;
  8. 美国最大的疆场是外交，中国最大的疆场是内部掌握生杀大权之人;
  9. 如果你失去了内斗的权力，基本就失去其他权力了;
  10. 就相当于现在习近平干的是以前周总理甚者都不如的领导干的事;
  11. 王岐山现在干的是毛主席的事;
  12. 中央委员总共有200多个委员;
  13. 中央总共是25个部门;
  14. 自建国开始毛主席是路线斗争，那时候贪污/作风都不是事;后来
      人们不信这一套了，到江泽民开始效法古人开始廉政/贪污斗争;
      这个想法确实是法古，古代皇上给你的就是让你活不下去的工资，
      这样你就必须得贪，皇上想打谁，闭着眼就能打。你活下去了，说明
      你贪了，你贪了，皇上那就放心了，说明他能控制的住你。
  15. 为什么说凤凰卫视是央视二台呢，“出口转内销”毛主席的发明，有些话
      没法在国内说，很多都是外国记者采访毛主席时，毛主席说的话，这些
      话再从外国人嘴里告诉国人，那感觉就不一样。
* XiJinPing 政治理念
  公方彬：習近平新政治觀的思想內涵和理論基礎

  2015年11月10日10:58 來源：人民網-人民論壇【摘要】 在探索中國的大國道路進程中，我
  們需要一位偉大的政治家，以重大理論突破實現黨的自我超越，實現民族的飛躍性發展，這
  個責任歷史地落在了習近平肩上。習近平的執政方略是“四個全面”，執政理念則是“新常
  態”，新政治觀就蘊含於其中。習近平的新政治觀是開創文明，這一政治觀由四大要素構成
  其理論體系，即政治規矩、利益共享、傳統一脈、合作共贏。從毛澤東的階級斗爭，到鄧小
  平的和平發展，再到習近平的開創文明，這是世界發展的必然反映，也是中國共產黨認識世
  界的飛躍。由此，我們的制度設計與價值目標將發生新的巨大變化，中國也將為人類文明注
  入新生力量。

** 【關鍵詞】新政治觀 習近平 中國共產黨 四個全面 社會共識

   當前，理論界乃至全社會有兩個需要下力氣解決的問題：一個是“左”右因缺少統一的價值
   坐標和評價標准而難達共識，爭論長期存在，這已經對黨創新執政方式、提高執政能力構成
   嚴重掣肘﹔另一個是對新一屆中央領導集體特別是習近平總書記治國理政思想和理念的解讀
   表面化、膚淺化，這同樣影響著全黨全社會達成共識、凝聚力量。兩個問題有著相同的根源，
   那就是中國共產黨由革命黨轉變為執政黨后，在理論建構上沒有實現相應突破，這樣就長期
   存在以革命理論指導執政行為的問題。如何解決這一問題？

** 歷史要求黨和國家最高領導人創新政治觀

   中國與西方國家比較，差異性並不僅僅在於走什麼道路的問題，或者說不僅僅是政治制度與
   社會運行規則的問題，更重要地反映在精神世界和價值系統的構成與邏輯方面。在三權分立
   的制度設計下，西方國家領導人的權力邊界清晰，職責范圍較窄，主要限定在行政范圍。所
   以，政黨輪替政府換屆，新領導人上任后，既不需要考慮立法和司法改革，也不需要重新設
   計國家政治結構和政治體制，更不需要建構一個新的精神大廈，引領社會思潮，制訂道德價
   值觀系統。因為西方的政治制度早就由開國元勛和一批思想家設計完成，立法和司法也由
   “三權分立”作出界定與分割，任何政黨執政都無權更易。至於精神大廈主要是由宗教信仰
   來構成，而宗教信仰又是不可更易的，是一種維系數千年不變的東西。即使從社會層面看問
   題，西方的道德本質上是宗教倫理道德，因而由宗教理論指導，由教會和社會公益組織推動，
   再加上完善的法律規范與深厚的契約意識，政府和領導人都不需要在這些方面花大氣力，這
   也是西方國家領導人工作內容單純的原因。

   中國的領導人遠沒有西方領導人那麼輕鬆，因為中國的宗教不具有支撐精神世界、引領社會
   道德的功能，而法的作用也處於發展過程中，我們社會最大的調整力量是黨及其領導下的政
   府，大眾的社會活動都是以政治活動為核心和評價尺度，一定意義上把中國界定為“政治中
   國”更為貼切，這也是中國人較西方人政治參與度更高的重要原因。反映在中國共產黨和國
   家最高領導人的責任方面，就是黨和國家領導人既要承擔政治設計的責任，還要承擔思想和
   精神引領的責任，這便決定了我們不僅要關注最高領導人的執政方略，更要關注執政方略背
   后的政治理念，也就是政治觀，這一點更帶有根本性。

   任何一種制度模式和社會運行規則都與國家民族的文化傳統、社會結構與價值觀念有關，無
   高下之分。既然我們是政治決定一切，那麼政治設計、思想引領、道德規范都由黨來承擔，
   進而對最高決策群體，尤其是最高領導人有極高的期待，他必須完成政治制度的完善與發展，
   必須找到政治思想的支撐和引領，必須完成社會道德體系的建構。這一切能否取得好的效果，
   取決於最高領導人的政治觀，有什麼樣的政治觀就產生什麼樣的政治設計，僅僅遵循前制，
   沒有實現重大突破者不算一代，隻有創造性的新政治觀才能開創新境界，所以，新政治觀是
   一代領導人的鮮明標志和評價尺度。

   如果以鮮明性、貢獻特質來認定中國幾代領導人，我們或許可以這樣評價，毛澤東的歷史貢
   獻反映在建黨建軍，鄧小平的貢獻反映在治國，習近平的貢獻將突顯於黨的執政能力的提升、
   民族人文品質的提升，反映在強化民族引領人類文明前行的能力，這些共同決定著中華民族
   的偉大復興。

   把共產黨領導的革命引向成功的是毛澤東，但在國家建設時期他的認識存在誤區，沒有跳出
   階級斗爭的束縛，結果出現了一個“貧窮的社會主義”。改善和引領中國共產黨實現轉型，
   或者說將中國共產黨由革命思維引向執政思維的是鄧小平，他解決了中國人一直無法解決的
   吃飯問題。鄧小平是最早參加中國革命的那一代人，貢獻巨大但不是主導者，他的貢獻主要
   是改變了中國共產黨的思維和價值系統，實現了一次重大超越，實現了治國理念的突破。在
   探索中國的大國道路進程中，我們需要一位偉大的政治家，以重大理論突破實現黨的自我超
   越，實現民族的飛躍性發展，這個責任落在了習近平肩上，原因在於兩個方面：首先，中華
   民族與中國共產黨都處於十字路口，要麼超越，要麼走彎路甚至歧路，沒有中間道路，這時
   需要引路人﹔再者，習近平已經展示出來的執政風格和執政能力，一個反腐和立規矩，就已
   經切入到改變中華民族價值觀的層面，令人刮目相看，且盡顯偉大政治家的品格和風採。

   進一步認識毛澤東、鄧小平與習近平的執政特點，會發現之間存在相通與區別之處。毛澤東
   之所以在“文革”中犯了重大錯誤仍然受到后人的高度推崇，主要是作為革命黨的領袖，無
   人比肩。他的政治理想和政治理論至今影響著黨的政治品質和性質宗旨。他在建黨建軍方面，
   貢獻巨大而不可替代。與此同時，我們又不得不承認，在執政方式和執政成效上，遠沒有領
   導革命那麼突出。主客觀的原因導致了毛澤東沒能超越歷史，超越自我。所以，如果提出毛
   澤東解決了什麼和沒有解決什麼這樣的問題，可以說從陳獨秀、向忠發、王明、博古、張聞
   天到毛澤東本人，都是圍繞馬克思主義革命理想在中國獲得實現的問題而展開，毛澤東是實
   現中國革命勝利的領路人，但他只是解決了革命這半程，沒有解決執政這半程。這就是看黨
   史軍史主要是看毛澤東的原因。

   主導國家建設走上以經濟建設為中心的軌道，推動中國共產黨完成由革命黨向執政黨的初步
   轉型，主要是鄧小平，鄧小平提出了工作重心轉移，尤其是確立了“和平發展”的政治觀，
   設計和主導了改革開放，由此使中國共產黨跳出“階級斗爭為綱”的政治觀。從1978年真理
   標准大討論到1992年南方講話，短短十幾年的時間，鄧小平就解決了中國的發展道路問題，
   在這方面無人可比。我們從鄧小平開啟的改革開放，可以領略思想解放的威力，由此折射出
   鄧小平的政治勇氣、政治智慧和政治品格。中國特色社會主義道路的總設計師是鄧小平，江
   澤民、胡錦濤等黨和國家領導人則根據這一設計，主要探尋了中國特色社會主義道路該怎麼
   走。回頭看改革開放，可以說黨能夠從封閉僵化中走出，就因為鄧小平以偉大政治家的胸懷
   和勇氣，採取了亞歷山大一劍破解“戈耳狄俄斯之結”的決斷，堅持“不爭論”，跳出“姓
   資姓社之爭”，一切以務實為原則，包括南海這樣的重大爭端，他也以“擱置爭議，共同開
   發”應對。正是有了鄧小平的思路和方法，才有了今天的世界第二大經濟體。不過，我們要
   承認，鄧小平並沒有真正從理論上解決中國的大國道路，這一歷史任務落在習近平的肩上。

   那麼，習近平面臨什麼挑戰，必須超越什麼？簡單地說，毛澤東和鄧小平兩人都沒有解決的
   或沒有面臨的許多重大歷史命題都集中到今天，需要習近平以偉大政治家的智慧和勇氣予以
   破解。毛澤東沒有解決階級斗爭之外的精神力量之源問題，鄧小平沒有解決經濟飛速發展后
   的利益分配或利益共享問題。兩個問題，一個涉及精神世界，另一個涉及物質世界。隻有將
   兩個問題都解決好，中華民族偉大復興才會成為現實。

   習近平要有效解決兩代領導人沒有解決的重大問題，不能重復兩人已經採取的方式方法，隻
   能自創新路，要在毛澤東和鄧小平的思想理論基礎上實現重大創新，或者說實現革命理論向
   執政理論的突破，才有可能破解中國共產黨遇到的新情況、新問題、新矛盾。毛澤東是在中
   國這樣的文化和社會環境中，運用從西方引進的馬克思主義先進理論完成中國革命的實際，
   鄧小平是在發現我們以往發展中的矛盾和問題的基礎上，探索前進道路，也就是仍然是在中
   國的特定環境中進行。習近平不可能再在這樣的環境中前進，他要超出中國以往積累的經驗
   范疇，不僅僅要考慮中國怎麼發展，而且要考慮中國和世界怎樣在互動中發展、甚至中國能
   否為世界探索一個更好的發展道路的問題。換句話說，毛澤東時代僅僅以批判和否定西方，
   就可以保証自己的合法性、先進性，而今國際國內的政治生態與民眾的觀念和思維已經走出
   很遠，僅僅是否定顯然無法說服人，無法贏得更多追隨者，習近平必須通過創造科學理論，
   並且是內生的理論為全社會找到共識，否則“左”右之爭將永遠進行下去。以中國參與世界
   規則制訂為例，

   _毛澤東時代搞了“三個世界劃分”_ _鄧小平時代搞了個“南南關系、南北關 系”_
   二者有差異，但都取決於 _二元政治觀_ 。在冷戰結束、世界政治生態發生巨大變化的今
   天，我們必須創新外交理論和國家關系准則，這決定於政治觀是否取得突破性進展。

** “四個全面”蘊含的新政治觀

   習近平的執政方略是“四個全面”，執政理念則是“新常態”，新政治觀就蘊含於其中。因
   此，我們分析其新政治觀必須弄清“四個全面”的基本內涵和政治品質。

   “全面建成小康社會”背后的政治品格和價值追求。確立什麼樣的國家和社會建設目標，反
   映的是執政集團的政治理想和執政理念，影響的是社會各階層的利益，這也是政黨高舉的旗
   幟和奮斗目標影響追隨者的重要原因，同時是接受人民群眾評價和檢驗的尺度。代表小部分
   人的利益必是小眾黨，代表大多數人的利益才敢言是最廣大人民利益的代表。政黨代表的階
   級利益不是一成不變的，它注定隨著政治生態的變化與政黨主導者的政治理念與政治設計處
   於變化之中。很多政黨在發展強大以后會發生蛻變，比如蘇共后期就蛻變為利益集團，國民
   黨之所以由號稱世界四大政黨到衰敗，也和它由為人民大眾利益而奮斗蛻變為“四大家族”
   的利益代表有關。然而，蛻變后的國民黨隻能依賴自己的利益集團，脫離了這個集團就會迅
   速走向滅亡，所以，國民黨不是不知道水能載舟也能覆舟的道理，但政治落后制約著其前進
   方向和道路。

   所以，對於中國共產黨來說，確立發展目標和實現路徑，很重要的是保持自己的政治品質，
   堅守政治倫理，力避背叛自己的宗旨。從這個意義上講，“全面建成小康社會”與鄧小平及
   其后來確立的“全面建設小康社會”存在一些差異。建成作為一種方略，作為習近平的政治
   觀表現出來，其內涵之豐富、意義之重大必是我們需要深刻把握的。

   確立全面建成小康社會的目標，至少蘊含著兩個重要的價值追求，一個是讓全社會共享發展
   成果，即解決利益分配懸殊過大的問題。建成既是目標，也是一種社會形態，還是一種價值
   觀，以建成作為我們的檢驗標准，那麼就涉及到社會發展成果的共享問題，就涉及到社會階
   層和集團的利益平衡問題，這就回到了共產黨“均貧富”“消滅剝削”“共享繁榮”的社會
   理想上來。如果我們全面理解習近平的舉措，就會深刻感受到他的政治理想與全面建成小康
   社會緊密結合在一起。比如限制特權是一種利益再分配，因為權力影響著利益，權力本身就
   是一種利益，是利益就要分享，這是現代政治觀的基本要求。再看反腐，這決不僅僅是消除
   腐敗，也存在著解決特權階層的利益壟斷問題，還是解決共享的問題。這也是習近平在紀念
   全國人大成立60周年大會上所指出的：“切實防止出現人民形式上有權、實際上無權的現
   象。”這個權包含著豐富的內容，包括生存權，也包括民主權利，充分體現在小康社會之中。

   另一個是將發展引向理性。當下我們建設的是小康社會，而不是全面建設發達國家，這與文
   革時期的超英趕美迥異，尤其是中國已經成為世界第二大經濟體的情況，理性殊為難得。如
   果全面建成小康社會只是停留在利益共享上，這個小康一定是存在偏差的，不穩定的，沒有
   希望的。因為，再偉大的政黨，再強有力的政府都不能滿足人無度的欲望，隻強調和激發物
   質利益需要，而不去引導價值觀，實現物質和精神的平衡，很可能經濟越是繁榮，物質利益
   越豐富，矛盾越多，風險越大。一個人沒有飯吃的時候隻有一件事要做，就是找飯吃，有了
   飯吃后會生出許多事來，而生出來的事一定是精神領域的。這就是習近平一再強調信仰，提
   出“人民有信仰，民族有希望，國家有力量”的重要原因。

   “全面深化改革”背后的政治邏輯和實現路徑。所有改革無非涉及兩個問題，一個是權力分
   配，另一個是利益分配。我們的體制改革一定遇到這樣一個問題，政府放權后，我們的制度
   特點與西方的制度特點有何差異？放權后，我們的政府還要不要維持如此龐大的規模？因為
   以前我們的政府作為市場主體參與經營，有人講“總理是最大的總經理”，如果政府退出經
   濟活動，向服務型政府轉變，那麼分配資源的能力必然下降，這時，中國的權力構成和運行
   會怎樣，很值得思考。

   改革的目的是興利除弊，但改革的實質和路徑則是創立一種新的游戲規則和邏輯。我們習慣
   於強調政治的神聖，並循著追求真理的路徑推進改革。歷史上走向失敗的政治改革，很重要
   的一點是沒有把握權力的本質與權力的運行規律。要保証政治體制改革有效推進，很重要的
   是去除政治絕對化和神聖化，讓政治權力運行回歸本質，也就是說政治制度改革其實就是打
   破舊的游戲規則，建立新的政治游戲規則。

   任何領域都有游戲規則，包括政治領域，如果不承認這一點，就很難解釋郭伯雄、徐才厚、
   令計劃之流的腐敗問題。按照原有的政治邏輯，這些人如果不清理，他們離開這個世界時，
   訃告上一定出現“忠誠的馬克思主義戰士”“我黨久經考驗的卓越的領導人”這樣的表述。
   這些溢美之辭放到革命戰爭年代走來的革命者身上是准確的，用孫中山先生的觀點，他們屬
   於“首義黨員”，是有高尚精神和堅定政治信仰支撐的，但放到和平時期成長起來的“協助
   黨員”和“普通黨員”身上，就不具有說服力，因為權力的漩渦中不會產生高尚，這是被現
   實所証明的，是不依集團和個人的意志為轉移的，隻有承認其間的特殊規則，才會建立新的
   有異於革命戰爭年代形成的政治規則。

   “兩個互不否定”，已經說明我們要以科學思維和政治觀指引改革探索，否則不僅無法找到
   新路，還會摧毀現有的精神和價值系統，導致紊亂。實際上，鄧小平與毛澤東選擇了不同的
   前進路徑，毛澤東在探索中國自己的道路時，革命階段的探索極其成功，但執政階段沒有成
   功的經驗可以借鑒，隻能自己找路，這便出現兩個結果，一個是成功，一個是失敗，毛澤東
   失敗了，但這個問題要辯証地看，沒有毛澤東的失敗，就沒有鄧小平的成功，也就不會有跳
   出“兩個凡是”，原本這就是對立統一規律使然。習近平主導中央政治局學習辯証法，堅持
   “兩個互不否定”，已經表明了自己的政治觀的出發點，而闡明的中國與西方和世界的政治
   關系，又表明了新的看法，也就是參與世界文明創造的新的政治觀念。

   “全面依法治國”背后的執政方式和執政理念。革命黨與執政黨、法治與人論，類似的問題
   都屬於繞不過、躲不開的難題，必須直面且需要作出理論解答。黨的理念處於革命階段，包
   括以革命理論支持執政階段，法只是實現“無產階級專政”的工具，因為調節社會和激發力
   量都來自於階級和革命，也就是說階級對立可以完成一切社會關系的處理。進入執政階段，
   尤其階級關系消失以后，社會矛盾主要反映為階層或集團的利益關系，黨不可能再以區分階
   級關系來完成社會調節，必須形成新的邏輯，即必須產生新的游戲規則和價值系統，這就必
   然選擇人類文化史上最具特色、最有成效的兩個規范方式，一個是契約亦即法治，另一個是
   道德規范亦或德治。從人類的更高級階段看，德治更可靠，但在人類尚未進入更高級階段時，
   隻能強調法治，輔之以德治。

   走法治道路，必然涉及到政治觀，換言之，沒有政治觀的突破，也便沒有法治的真正實施，
   這一點我們與西方是存在差異的。西方法治觀念深厚，早在公元前450年，羅馬廣場上就樹
   立了12銅表法，並由此奠定西方的法治基礎，同時這個基礎還得到了宗教的支撐，因為前有
   猶太教的摩西與上帝的約定，后有基督教的耶穌與上帝的約定，這些契約都支持法治，強化
   法治。

   全面依法治國與依法治國最大的差異在於，后者是治國的手段之一，而前者則是治國的根本
   乃至全部。這就意味著若干政治觀念必須確立起來。一個是“善於把黨的主張化為國家意
   志”，即實現觀念上的突破，把黨的治國理政思想注入法的范疇﹔另一個是黨的主導作用要
   在法的規范下活動，也就是黨帶領人民制訂的法應當帶頭執行，即強調自我約束，尤其要形
   成內生的邏輯和一致性，而不是“兩張皮”，否則難以跳出“黨大還是法大”的泥潭﹔再一
   個是努力把理論化作實踐，或者說將理論化作制度設計。

   依法治國不是新思想，這是鄧小平在改革開放初期就大力倡導的，所以我們高度關注全面依
   法治國，在於其更加豐富和深刻的內容。十八屆四中全會決定推進依法治國的一系列重大設
   計中，最為核心的是依憲治國，這實際上是習近平在紀念憲法頒布35周年大會講話中所突出
   強調的。依憲治國原本是現代國家的最顯著標志，之所以在當下中國成為熱點，主要是涉及
   “黨大還是法大”問題，涉及“宣誓效忠憲法與向黨旗幟宣誓”的問題，涉及現有憲法規定
   的一些公民權力如何落到實處的問題。

   一段時間來憲政成為敏感詞，其實，憲政道路漫長，並非一蹴而就。美國走的是西方資本主
   義制度下的憲政道路，但開國者設計的憲政思想，也是通過一次次由立法、司法、行政，乃
   至“升斗小民”參與的司法大戰方才實現。中國的憲政一定是社會主義制度下的憲政，這是
   不言而喻的，而保証真正實現憲政，也將有一個長期的過程，這期間不要為那些以西方憲政
   為評價尺度者詰難而動搖，而回避。所以，確立路徑就是一種政治觀念和政治路徑。

   執政和革命差異很大，走出“格瓦拉困境”，很重要的是為誰執政和怎樣執政，而這個問題
   背后又是為什麼執政，為執政而執政就會扭曲政治制度和政治目的，就會生成既得利益集團。
   這時的法律也就成了執政集團壟斷權力的手段，而不是公平正義的保護神。新的法治改革，
   提出了終生追究，領導干部打招呼要記錄在案，這就意味著，主要領導打著黨委領導司法的
   旗幟謀求一己之利不行了，就是謀取一個單位和地方的“公利”也不行了。這是一次巨大的
   具有政治特征的突破。

   “全面從嚴治黨”背后的政治倫理與廓清權力。習近平一再強調“政治規矩”，是因為這是
   全面從嚴治黨的路徑和不二選擇。政治規矩主要反映為兩個方面，一個是制度設計，另一個
   是遵循權力運行規則的意識，二者缺一不可。自然的人進化為社會的人，追逐的重點之一是
   權力。政黨政治與社會制度的先進與否，很重要地反映在對權力的授受關系的認識上，同時
   反映在權力建構和運行模式上。如果研究中國共產黨的自我更新路徑，突破口在於規范權力
   的運行。長期以來，我們的權力出現嚴重失控現象，一方面由於缺少強有力的外部監督，另
   一方面是中國的文化傳統原本潛規則重過顯規則。要改變這種情況，走西方政黨輪替和三權
   分立的道路是不現實的，根本出路在於自我改善，建立一黨執政下的政治倫理規則，也就是
   設計中國特色的將“權力關進籠子”的模式。

   當下中國迫切需要構建政治倫理規則，因為西方國家在政治權力之外還有宗教和法律起規范
   作用，我們的宗教不具有社會規范和調節力量，法治又處於發展進行時，且處於初級階段，
   很大一批領導干部尚未樹立法治意識，更願意依賴政治的強力，而政治權力的濫用很容易導
   致權力運行失序。中國歷史上有那麼多你死我活的政治斗爭，就在於科學制度規范缺失的同
   時，沒有形成政治倫理規則。

   習近平建構的政治倫理系統分幾個層次。第一個層次是政黨的路徑選擇。習近平堅守和傳承
   中國共產黨的“紅色基因”有其必然性。隻有堅守才能保証其擔任總書記的合法性，也就是
   其權力來自全黨的委托，而不是其他政治力量的委托。因此，他一再強調“共產主義信仰是
   共產黨員精神上的‘鈣’”，並且著力推動了群眾路線教育活動，重視中國共產黨“優良作
   風”的傳承與紅色基因的繼承，所有這些都反映在他一次次到紅色聖地去“朝聖”，等等。
   這實際上本身就是政治倫理使然，作為中國共產黨的總書記，有責任帶領全黨去探索，實現
   自我超越、自我更新，但決不能自我否定，前者可以帶來新生，后者隻能導致自我毀滅。即
   使從其家庭出身的角度講，他也不能搞自我否定，否則就會出現對先輩的背叛，這是個倫理
   問題。

   第二個層次是從嚴治黨。中國共產黨較西方政黨擁有更多道義優勢，至少理論上是這樣的。
   在過去很長時間裡共產黨一直佔領著道德的制高點，包括以犧牲自己來成就人民大眾，也包
   括對道德純潔的追求，只是在一段時間裡我們這種要求被廢馳了。這種廢馳有深刻的利益關
   系，正是利益關系決定了習近平強調從嚴治黨不是一個簡單地回歸傳統，而是新的開拓，因
   而包含著新政治觀。革命戰爭年代堅持更高的要求，黨和領導的軍隊沒有自己的利益，靠的
   是信仰，同時也是客觀環境使然，戰爭讓每一個參與者都無法保護自己的任何私財，這時黨
   要求高於一般群眾的純潔與無私，既是號召，也有客觀條件的配合。而今黨仍然沒有獨立於
   人民之外的利益，但黨的成員有自身利益，這種情況下講純潔，就必須奠基於新的政治倫理
   規則，這就意味著要以新政治觀為基礎。

   從嚴治黨主要包含兩個要素，一個是建立與時代特點相吻合的政治倫理，另一個是從嚴治官，
   以嚴治實現公權與私權的切割，以利益規范實現利益科學分配，由此平衡社會價值追求，真
   正形成先進國家早就實現的多元追求，而不是封建王朝傳承下來的官本位。多黨輪替不需要
   從嚴治黨，因為老百姓用選票來選擇執政黨，一黨執政在一定意義上高度控制資源，不到民
   怨發展到足以改朝換代的程度，執政者是可以保証自己掌握執政權力的，或者說西方換掉一
   個執政黨比較容易，中國換掉執政黨很難，正是這樣的原因，給中國共產黨提出了政治倫理
   要求，你要執政，你也想執政，你就必須把人民的利益看得高於一切，這是政治倫理規則決
   定的。

   第三個層次是精神境界。中國共產黨與西方政黨不同，西方政黨不會主動把自己神聖化，他
   們認為自己是政客，因為他們不靠這個來執政，中國共產黨卻是離不開自我神聖，因為隻有
   神聖才不需要政黨輪替。正是這種邏輯，就必須堅持對集團內成員的高要求，盡管很難做到。
   時代的變化和政治生態的變更，確實導致共產黨集團內的成員很難再達到革命戰爭年代那種
   革命熱情，那種奮斗精神，因此，在要求更高政治標准的同時，要加入時代元素，這實際上
   是新政治觀所關照的范圍。

** 習近平新政治觀的理論體系和基本構成要素

   習近平的新政治觀是開創文明，這一政治觀擁有四大基石，或者說由四大要素構成其理論體
   系。包括政治規矩、利益共享、傳統一脈、合作共贏。結合中國的政治和社會特點，政治規
   矩包含著黨紀和法治﹔利益共享包括經濟和政治權利﹔文化一脈則包含著傳統文化和政治文
   化的一脈，即打破過去以新文化否定舊文化，以新政治思維否定舊政治思維的老路﹔合作共
   贏則是在“命運共同體”基礎上的跳出冷戰的對立思維，以共有的文明和價值實現相向而行。

   習近平新政治觀的特點是，以新思維改變舊觀念，以新規矩更新舊秩序，即先立后破。這與
   毛澤東和鄧小平的政治觀有一脈相承之處，但也存在著一定的差異。毛澤東強調矯枉過正，
   先破后立，這反映在《好得很與壞得很》等文章中，更反映在文化大革命的一系列舉措中。
   雖然我們認為這些都符合革命的邏輯，出發點不能說錯，但卻導致了中華民族文化與價值觀
   的斷裂。鄧小平也走了這樣的道路，他打破了毛澤東的革命邏輯，跳出“兩個凡是”，但囿
   於歷史條件，他不得不採取“摸著石頭過河”的改革路徑，做法沒有錯，但在打破極左思想
   的同時沒有真正找到新路，換言之其改革開放總體缺乏理論指導，目前一直未能解決的
   “左”右之爭，盡管他一再要求跳出姓資姓社，但沒有解決內生理論，共識無法達成，斗爭
   隻能繼續。習近平“兩個互不否定”除了打通黨的精神血脈外，還由立而破，解決了過去革
   命思維下的先破后立而來的斷層和虛無。

   政治規矩。在十八屆中央紀委第五次全會上，習近平提出“政治規矩”。他說，要“嚴明政
   治紀律和政治規矩”“把守紀律、講規矩擺在更加重要的位置”。習近平講的政治規矩主要
   包括四個方面：黨章是總規矩﹔黨的政治紀律是全黨在政治方向、政治立場、政治言論、政
   治行動方面必須遵守的剛性約束﹔國家法律是黨員、干部必須遵守的規矩﹔黨在長期實踐中
   形成的優良傳統和工作慣例。習近平明確指出：“紀律是成文的規矩，一些未明文列入紀律
   的規矩是不成文的紀律﹔紀律是剛性的規矩，一些未明文列入紀律的規矩是自我約束的紀律。
   黨內很多規矩是我們黨在長期實踐中形成的優良傳統和工作慣例，經過實踐檢驗，約定俗成、
   行之有效，反映了我們黨對一些問題的深刻思考和科學總結，需要全黨長期堅持並自覺遵
   循。”也就是剛性約束與柔性約束的結合。

   政治規矩內含著兩個新元素，一個是黨由自律向他律拓展，也就是過去更多從政治上的先進
   性強調，未來則以完善制度來規范。同時，習近平一再強調敬畏權力，由此展開，必然涉及
   到政治活動的范圍，涉及到黨在什麼范圍內活動的問題，必然是改變過去那種政治解構一切，
   堅持黨在法的范圍內活動。其實，這其中還有一個重要理念，就是法治為主，德治為輔。中
   國的封建統治是宗法，統治者要維護其家天下，自然不會走法治道路，隻能選擇德治。中國
   共產黨確立的全心全意為人民服務的宗旨與核心價值觀，以及我們黨靠純潔性和神聖性形成
   強大的號召力，這些都是政治優勢，但我們也必須遵循政治規則，因為政治生態的變化已經
   不再支撐以道德規范行為，處理不好，權力的特有規律甚至形成“逆塑造”現象，即在權力
   體系中呆得時間越久，越不道德，所以，必須尋求與時代相適應的新的權力運行規則。所以，
   今天繼續要求黨員干部提升自己的境界，堅守共產黨人的政治品德，但基礎卻是政治倫理規
   則，這應當是習近平提出政治規矩的基本考量，也是革命黨轉變為執政黨的最大公約數和最
   重要的突破口。

   利益共享。任何國家制度設計的核心無不是利益分配問題，衡量一個政黨先進與否，就要看
   其代表哪個集團和階層的利益，即使西方非政治制度之爭的政黨競選，也是看代表了多少選
   民的利益。對於中國共產黨來講，“代表最廣大人民群眾的利益”，既是性質宗旨的要求，
   也是獲得政治力量、精神力量的源泉所在。評價一個政黨乃至一個人的精神境界，最重要的
   指標也是利益予奪。我們分析社會主義與資本主義的差異，最關鍵的是以何種分配方式進行
   利益劃分。比如，核心價值觀上，西方早期強調的是自由、平等、博愛，為什麼平等很快淡
   出了呢？主要是因為市場經濟或股份制經濟。西方人認為，實現法律和人格上的平等是能夠
   做到的，但要實現社會地位的平等則不可能，因為市場經濟遵循的是“股同權同，股不同權
   不同”，老板與員工從來都是不平等的，也永遠無法實現平等。而在社會主義中國，革命的
   理由就是推翻階級剝削，實現人與人的平等，這也是對勞苦大眾具有強大號召力的根本原因。
   改革開放后，由於我們的制度設計出現了錯位，結果出現了貧富懸殊的問題，導致矛盾叢生。

   習近平的政治觀與執政理念、執政方略正在回歸到中國共產黨的性質宗旨和奮斗目標上來。
   中國共產黨的性質宗旨是什麼？實現共產主義而共產主義的根底就是“沒有剝削和壓迫”，
   而共產主義的中繼社會主義，也是強調共同富裕，在社會主義初級階段，我們出現了偏離，
   主要就是利益分配出了問題。習近平正在通過深化改革來解決這個問題，並且是全方位和立
   體式的，比如限制國有企業高管的工資，就是一種調整分配方式的改革，反腐和規范權力，
   消除權力尋租的空間，也是一種利益分配方式，並且更帶有根本性和深層次。權力影響著利
   益，權力本身就是一種利益，是利益就要分享，當我們的利益分配深及這樣的層次后，一種
   現代的政治文明就注入了執政理念和邏輯。這顯然是習近平的新政治觀所關照的方面。

   傳統一脈。習近平一個重要思想是“兩個互不否定”，即不以改革開放前30年否定改革開放
   后30年，也不以改革開放后30年否定改革開放前30年。他特別強調辯証法和歷史唯物主義，
   強調不能脫離開特定的歷史條件看問題，尤其不能以當下的標准評價歷史。這一點對於我們
   確立正確的思維方式和思想方法很重要，對於我們這個尤其重視歷史的國家和民族很重要。

   中國與西方在價值坐標上的重要差異是歷史觀。中國有悠久的歷史，這其間有驕傲也有屈辱，
   我們要在歷史中獲得革命的力量，所以強調“忘記過去就意味著背叛”，我們評價現實更主
   要的是以歷史為主軸和尺度。西方更重視往前看，或者說重視過去更重視未來，因為他們的
   價值判斷和精神力量之源並非來自歷史，而是源自宗教信仰與核心價值。僅以宗教信仰為例，
   我們的多神教強調輪回，因而歷史就變得重要，西方的猶太教和基督教都是一神教，這是一
   個有起點無終點的永恆追求。再看核心價值，西方的核心價值是由思想家從社會生活中提煉
   出來的，我們的核心價值是由黨的政治觀和執政需要確立起來的。這種差異也決定著思維方
   式和價值取向的差異，西方既然不以政黨為主軸，那麼誰創造了什麼樣的輝煌都不重要，關
   鍵是看還能創造出什麼。我們既然是與黨聯系在一起的，那麼就必須維系黨的神聖和高尚，
   因而就必須從多黨斗爭最后獲得勝利者那裡找根據，這也是我們的價值坐標和評價標准都是
   以中國共產黨革命與新中國成立為根本的原因。

   其實，任何一種思維方式和價值系統都有存在的合理性，至少階段性上是這樣。既然如此，
   我們就不需要或者不必過多討論，而更應看我們怎樣才能跳出以否定過去証明當下，以否定
   他人証明自己的思維定勢。這些問題不能得到徹底解決，中國共產黨以致全社會就會一直困
   於“左”右之爭的泥潭，就永遠無法達成共識，聚合力量。而要解決這樣的問題，思維方式
   和思想方法的突破尤為重要，要找到自己的歷史邏輯，同時找到自己的前進方式與超越自我
   的路徑。習近平的政治觀與思想路線能夠解決這樣的瓶頸或桎錮。

   合作共贏。習近平的合作共贏，既是中國外交理論的突破，更是政治觀的突破。看一下新中
   國成立以來60多年間的外交思想和處理國家關系准則就很清楚。依據世界政治生態與中國的
   國情，毛澤東確立了三個世界劃分、五項基本原則和不結盟，這完全是建立在世界二元對歭
   的政治生態之上。鄧小平依據變化了世界，認為世界大戰較長時間內打不起來，和平與發展
   是世界主軸，由此開始了與世界特別是西方國家的互動。在冷戰結束、世界政治生態發生巨
   大變化的今天，中國要發揮大國的作用，必須處理與各國的關系，特別是與美國等西方發達
   國家的關系，這就需要跳出冷戰思維與零和博弈，真正為“中國夢與美國夢是相通的”打下
   理論基礎。

   為什麼西方不太相信中國和平崛起？他們認為，共產黨的黨章與中國的憲法都把消滅資本主
   義作為終極追求，怎麼可能走到一起來建設世界？由此來看，在不動搖自己的精神大廈的情
   況下，要走通中國的大國道路，就必須實現政治觀上的突破，把習近平的“萬邦和諧、萬國
   咸寧”或者說“協和萬邦”的國際觀與外交理念納入外交設計，尤其是把習近平開拓世界文
   明的思想奠基於此。深刻認識世界文化的普遍規律與多樣性，把以包容推動世界文明不斷進
   步的思想確立起來。

   認識習近平“開創文明”的新政治觀，決不是一個符號，而是蘊含著深刻的思想，同時又表
   現在我們的價值判斷與行為方式中。以革命的思維和二元價值判斷指導我們，結果一定是把
   世界分為兩大陣營。如果正確把握“太平洋容得下中國和美國”“中國與美國共鑄大國關
   系”等論述的寓意，結論一定是“跳出冷戰思維和零和博弈”，一定是跳出制度對抗，以人
   類文明為主軸和著眼點，共同探求世界規則與文明前進方向，這是中國共產黨和中國人民認
   識世界方面的巨大突破。從毛澤東的階級斗爭，到鄧小平的和平發展，再到習近平的開創文
   明，這是世界發展的必然反映，也是中國共產黨認識世界的飛躍，由此，我們的制度設計與
   價值目標將發生新的巨大變化，中國也將為人類文明注入新生力量。

   （公方彬，國防大學軍隊政治工作教研室副主任、教授、正師職研究員。研究方向為軍隊作
   風、廉政建設。主要著作有《決策中國》《價值中國》《精神中國》《思想的原野》等。）
